# project definitions
project: Quassel IRC
audience: designers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/quassel/designers
topnav_title: Quassel IRC
homepage_title: Quassel IRC
site_title: Quassel IRC
project_folder: quassel
company_name: Quassel IRC
footer_image_location: ../common_images/bluemarine_logo.png
github_editme_path: quassel/quassel/edit/reviews
#disqus_shortname: quassel
# variables


sidebar_tagline: Quassel
sidebar_version: Latest version 0.x.y
theme_file: theme-blue.css
pdf_file_name: quassel_designers_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_designers'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/quassel_writers*

# same for all
host: 127.0.0.1
feedback_email: mail@quassel-irc.org

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: false
      search: true
      tooltip: true

