# project definitions
project: quassel_writers
audience: writers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/quassel/writers
topnav_title: Jekyll Documentation Theme
homepage_title: Jekyll doc theme for writers
site_title: Jekyll theme for writers
project_folder: quassel
company_name: Your company
footer_image_location: ../common_images/company_logo.png
github_editme_path: tomjohnson1492/documentation-theme-jekyll/edit/reviews
disqus_shortname: idrbwjekyll
# variables


sidebar_tagline: Writers
sidebar_version: Version 4.0
theme_file: theme-green.css
pdf_file_name: quassel_writers_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_writers'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/quassel_writers*

# same for all
host: 127.0.0.1
feedback_email: tomjohnson1492@gmail.com

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

